import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import { Wallet } from '../near-wallet'
import { Contract } from '../near-interface'

const CONTRACT_ID = 'dev-1672748799344-89158998807600'

export default function Home() {
  const [useWeb3, setUseWeb3] = useState({})

  useEffect(() => {
    const fetchData = async () => {
      const wallet = await new Wallet({ createAccessKeyFor: CONTRACT_ID })
      const contractInstance = new Contract({ contractId: CONTRACT_ID, walletToUse: wallet })
      const isSignedIn = await wallet.startUp();
      setUseWeb3({
        wallet,
        contractInstance,
        isSignedIn
      })
    }

    fetchData()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <button onClick={() => useWeb3.wallet.signIn()}>Connect Wallet</button>
          <button onClick={() => useWeb3.wallet.signOut()}>Sign out</button>
          <div>{useWeb3?.wallet?.accountId || ""}</button>
        </div>
      </main>
    </>
  )
}
